FileVersion = 1
Dependencies = {corlib = "*", GLFW = "*", ImGui = "*", OpenGL = "*", ImGuiImplGlfw = "*", ImGuiImplOpenGL3 = "*"}

[Project]
Name = "Example"
TargetType = "BeefGUIApplication"
StartupObject = "Example.Program"
