FileVersion = 1
Dependencies = {corlib = "*", ImGui = "*"}

[Project]
Name = "ImGuiImplOpenGL2"
DefaultNamespace = "ImGui"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/../dist/x64/Debug/cimgui.lib"]
